WASdev/azure.liberty.aro

README.md
pom.xml
src/main/arm/createUiDefinition.json
src/main/arm/mainTemplate.json
src/main/arm/parameters.json
src/main/cli/deploy.azcli
src/main/scripts/get-object-id.sh

The PR is to resolve the following issues:
* Resolve #12 
* use deployment script to get object ids
* get object IDs from user input or deploymentScript
* Failed to get object IDs with deploymentScript if the user-assigned managed identity doesn't have an application administrator role in Azure AD;
* Successfully deployed a Java app on an ARO cluster with object IDs retrieved by deploymentScript if the user-assigned managed identity has an application administrator role in Azure AD;
* Successfully deployed a Java app on an ARO cluster with user input object IDs;
Here is the [preview link](https://portal.azure.com/#create/microsoft_javaeeonazure_test.20191212-arm-rhel-was-nd-v9-cluster-previewazure-liberty-aro) for …

Support to get object IDs from deploymentScript or user input

---

pom.xml
src/main/arm/mainTemplate.json
src/main/scripts/install.sh

Reza tested the [preview link](https://portal.azure.com/#create/ibm-usa-ny-armonk-hq-6275750-ibmcloud-aiops.20210823-liberty-aro-previewliberty-aro) today and I found an issue which is not observed before: The open-liberty-operator deployment seems hang. The root cause seems the subscription `open-liberty-certified` is not created which caused the `open-liberty-operator` is not deployed either.  
* Wait until subscription open-liberty-certified created
* Expose `containerRegistryUrl` in outputs of deployment
Tested using Azure CLI command and [preview link](https://portal.azure.com/#create/microsoft_javaeeonazure_test.20191212-arm-rhel-was-nd-v9-cluster-previewazure-liberty-aro) of testing offer, the issue is not reproduced.

Improve stability of azure.liberty.aro offer

---

README.md
pom.xml
src/main/arm/createUiDefinition.json
src/main/arm/mainTemplate.json
src/main/arm/parameters.json
src/main/cli/deploy.azcli
src/main/cli/uploadApp.azcli
src/main/scripts/create-sp.sh

The PR is to resolve the following issues:
* Resolve #28
* Create service principal within deploymentScript
* Update label from `Pull secret` to `Red Hat pull secret`
* Show error msg if none or multiple UAMIs are selected
* Remove existing app package from storage account before uploading
* Failed to create service principal with deploymentScript if the user-assigned managed identity doesn't have an application administrator role in Azure AD;
* Successfully deployed a Java app on an ARO cluster with client ID/client secret/object IDs retrieved by deploymentScript if the user-assigned managed identity has an application administrator role in Azure AD;
* Successfully deployed a Java app on an ARO cluster with user …

Enhancement of liberty on aro offer

---

pom.xml
src/main/scripts/create-sp.sh

The PR is to resolve the following issues:
* Resolve #44
* Enhance deployment script `create-sp.sh` to check if Contributor role (or Owner role) is granted to the uami before deploying Azure resources
* The uami has no access to the subscription: Deployment failed fast
* The uami has Reader role in the subscription: Deployment failed fast
* The uami has Contributor role in the subscription: Deployment succeeded
Here is the [preview link](https://portal.azure.com/#create/microsoft_javaeeonazure_test.20191212-arm-rhel-was-nd-v9-cluster-previewazure-liberty-aro) for live testing.

Check the permission of the uami

---

pom.xml
src/main/arm/createUiDefinition.json
src/main/arm/mainTemplate.json
src/main/scripts/create-sp.sh
src/main/scripts/import-image.sh
src/main/scripts/install.sh

The PR is to resolve the following issues:
* Follow-up for PR #45
* Resolve #47 
* Whether uami has the required permission in the subscription is always checked
* Only create the client application when required
* Add image path example as placeholder text
* Request a public image in the info box
* Check if the source image is valid and exit with the appropriate error message if not
* Remove unnecessary error messages from the list when the deployment failed 
* Successfully deployed the application with the user specified docker image path: `websphere-liberty`
* Failed to deploy the application with the incorrect docker image path: `websphere-liberty-not-found`
Screenshot for the enhanced **Configure application** …

Always check if the uami has the required permission in the subscription and check if source image is valid

---

pom.xml
src/main/scripts/install.sh
src/main/scripts/open-liberty-application.yaml.template
src/main/scripts/open-liberty-operator-subscription.yaml

The PR is to resolve #49 by upgrading open-liberty-operator to 0.8.0.
Here is the [preview link](https://portal.azure.com/#create/microsoft_javaeeonazure_test.20191212-arm-rhel-was-nd-v9-cluster-previewazure-liberty-aro) for live testing.

upgrade open-liberty-operator to 0.8.0

---

pom.xml
src/main/arm/createUiDefinition.json

The PR is to fix #53 by adding a new option of deploying the Open Liberty sample image in the UI:
* Deploy user own application image:
* Deploy the Open Liberty sample image:

Add Open Liberty sample image option

---

pom.xml
src/main/scripts/create-sp.sh

The PR is to resolve #59. Based on the analysis of issue #59 , the PR is to add a delay (30s) after sp is created, in order to wait it available for role assignment in the ARM template later.
Tested for 5 times, the role assignment to the created service principal all succeeded.

Add delay to wait sp available for role assignment in ARM template

---

pom.xml
src/main/scripts/install.sh

The PR is to increase the max retries in order to wait until the Open Liberty Operator is available, to resolve #60.
Tested for 5 times, all deployments succeeded.

Increase max retries to wait until the Open Liberty Operator is available

---

.github/workflows/package.yaml
pom.xml
src/main/arm/parameters.json
src/main/scripts/install.sh

The PR is to resolve #70, with the following changes:
* Add a new method `wait_project_created` with retry mechanism to improve the resilience of creating project/namespace.
* Add a new method `wait_image_imported` with retry mechanism to improve the resilience of importing user specified app image.
* Add a new method `wait_resource_applied` with retry mechanism to improve the resilience of deploying `OpenLibertyApplication` custom resource with user specified app image.
* Enhance the existing method `wait_route_available` with retry mechanism to improve the resilience of getting the route host of deployed app.
* Successfully deployed the ARO 4 cluster with the Open Liberty sample image or user specified app image. …

Fix the issue that the app image is not successfully deployed

---

.github/workflows/package.yaml
pom.xml
src/main/arm/mainTemplate.json

Upgrade versions of external deps used in pipelines by referencing to the centralized config file:
- arm-ttk
- azure-javaee-iaas
The other changes:
- upgrade to Azure resource api versions
- work around arm-ttk test 'VMSize parameter must be declared for the parent template'
Successful ran of `package` pipeline:
* https://github.com/majguo/azure.liberty.aro/actions/runs/3269776966

Upgrade versions of external deps used in pipelines by referencing to the centralized config file

---

.github/workflows/integration-test.yaml
.github/workflows/setup-credentials.sh
.github/workflows/tear-down-credentials.sh
README.md
pom.xml
src/main/arm/createUiDefinition.json
src/main/arm/mainTemplate.json
src/main/arm/parameters.json
src/main/cli/deploy.azcli
src/main/resources/README.md
src/main/scripts/catalog-source.yaml
src/main/scripts/install.sh
src/main/scripts/open-liberty-operator-subscription.yaml
src/main/scripts/websphere-liberty-application.yaml.template
src/main/scripts/websphere-liberty-operator-subscription.yaml

The PR is to simplify the user experience by resolving the following issues:
* Resolve #74
* Update UI to support install WebSphere Liberty Operator
* Update ARM templates to support WLO
* Update scripts to support WLO
* Add two more templates for support `WebSphereLibertyApplication` CR
* Add `integration-test` pipeline which supports WLO
Verified the following 4 test cases with `integration-test` pipeline (**Note**: For all cases enabled with **WLO**, **Edition** is `IBM WebSphere Application Server` and **Product entitlement source** is `Standalone`):
|WLO	|OLO	|Sample App|Pipeline run|
|-----|-----|----------|------------|
|X    |     |X         |[integration-test-13](https://github.com/majguo/azure.liberty.aro/actions/runs/3390259657)|
|X    |     | …

Support WebSphere Liberty Operator

---

.github/workflows/integration-test.yaml
pom.xml
src/main/arm/createUiDefinition.json
src/main/arm/mainTemplate.json
src/main/scripts/preflight.sh

The PR is to fix the following issues:
* Resolve #79 
* Update instructions about creating service principal by adding `sleep 30`
* Add a preflight script which 
* fails the deployment if object Id of the service principal is empty
* wait 30s to make the service principal is available in the role assignment later
* Deploy ARO 4 + WLO + Sample app: [integration-test-33](https://github.com/majguo/azure.liberty.aro/actions/runs/3636397576)
* Deploy ARO 4 using [preview link](https://portal.azure.com/#create/microsoft_javaeeonazure_test.20191212-arm-rhel-was-nd-v9-cluster-previewazure-liberty-aro)
The command to create service principal is updated from `az ad sp create-for-rbac --sdk-auth` to `out=sp-$(date +%s).json && az ad sp create-for-rbac --sdk-auth > ${out} && sleep 30 && cat ${out} | …

Wait service principal available

---

.github/workflows/integration-test.yaml
pom.xml
src/main/scripts/install.sh
src/main/scripts/open-liberty-application.yaml.template
src/main/scripts/open-liberty-operator-subscription.yaml

The PR is to resolve #91 (and also resolve #68) which updates OLO to 1.2.0 and CR `OpenLibertyApplication` to `apps.openliberty.io/v1`.
The following workflow runs complete successfully:
* Install OLO: [integration-test-38](https://github.com/majguo/azure.liberty.aro/actions/runs/4987499936)
* Install WLO: [integration-test-39](https://github.com/majguo/azure.liberty.aro/actions/runs/4988233402)

Update OLO to 1.2.0

---

.github/workflows/package.yaml
pom.xml
src/main/arm/mainTemplate.json
src/main/scripts/catalog-source.yaml
src/main/scripts/open-liberty-operator-subscription.yaml

The most recent offer publish in Partner Center failed as the support replied that the `mainTemplate.json` is invalid. Th PR is to remove comment from `mainTemplate.json` to try fix the issue.

Remove comment from mainTemplate.json

---

docs/trouble-shooting-guide.md
pom.xml
src/main/scripts/open-liberty-operator-subscription.yaml

The PR is to fix the most recent deployment issue reported by @edburns and @m-reza-rahman. Per investigation, the root cause is that when the new version `1.2.2` of OLO is available, the `startingCSV` doesn't work with `open-liberty-operator.v1.2.1` anymore. Updating to `open-liberty-operator.v1.2.2` solves the issue. 
Please see the similar issue for olo `1.2.1` described in https://github.com/WASdev/azure.liberty.aro/pull/97#issuecomment-1626388789.
I successfully installed OLO 1.2.2 with the fix of the PR and also successfully deployed the sample app.
* ![image](https://github.com/WASdev/azure.liberty.aro/assets/10357495/d1b7ca41-9775-4917-9c90-37bd06b6e3b2)
* ![image](https://github.com/WASdev/azure.liberty.aro/assets/10357495/29b90a64-e9f1-4c05-b57c-cce8240b841f)
Signed-off-by: …

Upgrade olo to 1.2.2 manually

---

pom.xml
src/main/scripts/install.sh

The PR is to fix #107 (liberty on aro offer deployment failure) which was caused by the issue that the installed `oc` client doesn't work. The fix is inspired by [Installing the OpenShift CLI on Linux using the web console](https://docs.openshift.com/container-platform/4.14/cli_reference/openshift_cli/getting-started-cli.html#cli-installing-cli-web-console_cli-developer-commands).
The deployment succeeded with the fix, see [integration-test](https://github.com/majguo/azure.liberty.aro/actions/runs/7442786774).

Fix deployment failure

---

src/main/scripts/install.sh
src/main/scripts/open-liberty-operator-subscription.yaml

This PR is to addressing issues detected when running integration tests against PR #108:
* OLO installation failed due to the channel is not updated to `v1.3`
* wget failed due to `certificate verification failed: self signed certificate in certificate chain`
The integration test pipeline ran successfully with the fix included in this PR:
* [integration-test](https://github.com/majguo/azure.liberty.aro/actions/runs/7523685431)

Fix issues detected when running integration tests against PR #108

---

pom.xml
src/main/scripts/open-liberty-operator-subscription.yaml

The PR is to fix the OLO deployment issue by updating it to `1.3.3`.
Integration test succeeded: https://github.com/majguo/azure.liberty.aro/actions/runs/10914188313

Update to olo 1.3.3

---

pom.xml
src/main/arm/createUiDefinition.json

See https://learn.microsoft.com/en-us/partner-center/marketplace-offers/azure-container-troubleshoot#publishing-fails-with-resourcegroup-allowexisting-must-be-set-to-true-in-the-createuidefinitions-config-error.

Enable deployment to non-empty resource groups

---

pom.xml
src/main/scripts/open-liberty-operator-subscription.yaml

The version of Open Liberty Operator shipped with Azure Red Hat OpenShift cluster deployed by the offer has been upgrade to `1.4.1`, which caused the deployment failure as the offer tries to deploy OLO `1.4.0`. The PR is to update the OLO version according to fix the deployment failure.

Update version of OLO to 1.4.1

---

.github/workflows/integration-test.yaml
.github/workflows/package.yaml
pom.xml
src/main/scripts/install.sh
src/main/scripts/open-liberty-operator-subscription.yaml

This pull request includes several updates to configuration files, scripts, and versioning to fix deployment issues, enhance functionality and compatibility. The most important changes are grouped by theme below:
* [`src/main/scripts/install.sh`](diffhunk://#diff-b045766e8db5f9b67ba7d8d2e7cfee92679195513f737f83c5e9bfe943de4b40R371-R379): Added a check for the existence of `/usr/lib/libresolv.so.2` and installed the `gcompat` package if necessary, including creating a symbolic link to ensure compatibility with the OpenShift CLI.
* [`src/main/scripts/open-liberty-operator-subscription.yaml`](diffhunk://#diff-f6fd7ee96bc830c1d1cd694c2a7ae5ad7ebb0fb49246033f84bb0e053945a4dcL22-R22): Updated the subscription channel from `v1.3` to `v1.4` for the `open-liberty-certified` operator.
* …

Fix deployment issues: update version of OLO to `1.4.1` and install missing library for `oc` cmdlet

---

pom.xml
src/main/scripts/open-liberty-operator-subscription.yaml

The PR is to fix deployment failure (The Open/WebSphere Liberty Operator is not available) by upgrading version of OLO to `1.4.2`.
It also rolls back the version of `vNetRoleAssignment` to `2022-04-01` to fix the regression issue introduced in #134 (details pls see this [comment](https://github.com/WASdev/azure.liberty.aro/pull/134/files#r2061958597)).
OLO: [integration-test #103](https://github.com/majguo/azure.liberty.aro/actions/runs/14685783109)
WLO: [integration-test #104](https://github.com/majguo/azure.liberty.aro/actions/runs/14687688899)

Update version of OLO to 1.4.2

---

.github/workflows/integration-test.yaml
.github/workflows/package.yaml
pom.xml

In light of recent incidents involving GitHub Actions ( [https://www.stepsecurity.io/blog/reviewdog-github-actions-are-compromised](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fwww.stepsecurity.io%2fblog%2freviewdog-github-actions-are-compromised&data=05%7c02%7cEdward.Burns%40microsoft.com%7c2e164dbc41814a70b33808dd827ed367%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c638810203429735777%7cUnknown%7cTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7c0%7c%7c%7c&sdata=vi16rlxw83McXqhRG1wMrm4LQ4i26aSyHYWywOPY9K8%3D&reserved=0), [https://www.theregister.com/2025/03/17/supply_chain_attack_github/](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fwww.theregister.com%2f2025%2f03%2f17%2fsupply_chain_attack_git …

Update actions version with pinned hash value 
